{"uuid": "99ff6e83-0d1e-4632-8d3d-24e671750cdf", "children": ["3ae66c98-347e-4da9-b36f-0fed9b568903", "3e71707a-fd06-4d41-8687-1d232f69745e", "c457de8c-02c5-43ff-9f1f-58bc59b56de7", "32d76fd1-2cff-4b74-8ea6-edbb7ba4ef65", "8152b5b1-10fa-4dd0-8962-6c2c3e7b2ffb", "c52a1681-9428-4a0b-8291-d759a56a7f78"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1645108491762, "stop": 1645108491762}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=98.0.4758.102)\n\n", "trace": "  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\ajayb\\PycharmProjects\\PageObjectModelFramework\\PageObjectModelFramework\\Testcases\\conftest.py\", line 24, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"dologin\", attachment_type=AttachmentType.PNG)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1064, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1074, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1645108513953, "stop": 1645108527621}], "start": 1645108491762, "stop": 1645108527621}